name: Create Issue on Org Member

on:
  repository_dispatch:
    types: [org-member-added]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue@v4
        with:
          title: ${{ github.event.client_payload.title || 'New Member Joined' }}
          body: ${{ github.event.client_payload.body || 'No description provided.' }}
